services:
  mongo:
    image: mongo:7
    container_name: pyqwithme-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - pyqwithme_mongo_data:/data/db

volumes:
  pyqwithme_mongo_data:
